Switch to using clone element
ooade/react-click-away-listener pull request #28
Opened 2021-01-26 09:13 UTC by ooade

2021-01-26 13:22 UTC, jblevins1991 requested changes

2021-01-26 13:22 UTC, jblevins1991 commented on src/index.tsx
> +	children: React.ReactElement;
Can we get an interface that adds concrete types to props?

2021-01-26 13:22 UTC, jblevins1991 commented on src/index.tsx
>  	onClickAway: (event: Events) => void;
Need to forwardRef to child component. If we don't then refs cannot be passed to component libraries like material ui

2021-01-27 06:50 UTC, jblevins1991 commented on src/index.tsx
>  		ref: node,
This breaks code from component libraries. If I have a TextField from material-ui and I want to hide the TextField onClickAway and also want to pass a ref to the TextField to handle focusing the component within my component I cannot. Here is a useful mergeRefs function I have found and used in my projects to solve this. You can merge the forwarded ref with the `node` ref easily.

```
import * as React from 'react'

const mergeRefs = <T = any>(
  refs: Array<React.MutableRefObject<T> | React.LegacyRef<T>>
) => {
  return (value: any) => {
    refs.forEach((ref) => {
      if (typeof ref === 'function') {
        ref(value)
      } else if (ref != null) {
        (ref as React.MutableRefObject<T | null>).current = value
      }
    })
  }
}

export {
  mergeRefs
}

export default mergeRefs
```

You would just need to do the following
```
const handleRef = mergeRefs(forwardedRef, node)

...

return React.cloneElement(children, {
  ref: handleRef,
  onClick: handleBubbledEvents,
  onTouchEnd: handledBubbledEvents,
  ...children.props,
})
```

children.props also has to be passed to the cloned element.

2021-01-27 08:36 UTC, ooade commented on src/index.tsx
>  	onClickAway: (event: Events) => void;
Why? It's unnecessary. refs shouldn't be added to the click away listener now that it's sitting on the child component.

If a ref is needed, it could be applied to the child component and not the click away component.

Or what am I missing?

2021-01-27 13:42 UTC, ooade commented on src/index.tsx
>  		ref: node,
Taking a second look at it, there really isn't need to forward the ref. Especially now that we're just adding the listener to the Cloned children. 

If a ref is attached to the cloned child, it won't be affected.

2021-01-27 14:49 UTC, jblevins1991 commented on src/index.tsx
>  		ref: node,
Think about this code right here.

```
import * as React from 'react'
import Button from '@material-ui/Button'

const MyCustom = () => {
  const myRef = React.useRef(null)
  
  return <ClickAwayListener onClickAway={handleClickAway}>
    <Button ref={myRef}>
      Click me!
    </Button>
  </ClickAwayListener>
}
```

Your code overrides the ref I am passing to the Button component. So when my code runs, that ref is no longer attached to the Button component.

2021-01-27 18:28 UTC, jblevins1991 commented
I will pull this branch later and test it. The code looks good so far.

2021-01-28 05:43 UTC, jblevins1991 commented on src/index.tsx
> +		const handleBubbledEvents = (event: Events | null) => {
Don't use `Event | null` for the type. Typescript has the `?` optional operator to handle this. By using null, you always have to pass an argument to the function.

2021-01-28 05:46 UTC, jblevins1991 commented on src/index.tsx
> +			document.addEventListener(mouseEvent, handleEvents);
By using react's `onClick` event and `onTouch` event you don't have to bubble up the events manually. All events in React bubble up to the document. You also could accomplish this by adding the third parameter to the addEventListener, but using level 2 DOM listeners is less than ideal as the events are not controlled by React's synthetic events.

2021-01-28 08:16 UTC, ooade commented on src/index.tsx
> +		const handleBubbledEvents = (event: Events | null) => {
Yeah, that was actually an oversight

2021-01-28 19:21 UTC, ooade commented
@jblevins1991 I've fixed most of your concerns. You can test and give feedback. I've published a [beta package](https://www.npmjs.com/package/react-click-away-listener/v/2.0.0-alpha.4) so you don't have to pull the repository to test.

Thanks!

2021-01-29 02:23 UTC, jblevins1991 commented
> @jblevins1991 I've fixed most of your concerns. You can test and give feedback. I've published a [beta package](https://www.npmjs.com/package/react-click-away-listener/v/2.0.0-alpha.6) so you don't have to pull the repository to test.
> 
> Thanks!

I copied the code file and everything seemed to work well. I am going to approve the pull request.

2021-01-29 02:23 UTC, jblevins1991 approved these changes

2021-02-06 21:44 UTC, merged